files:
  image: postgres:9.4
  command: '/bin/true'
db:
  image: postgres:9.4
  volumes_from:
    - files
  volumes:
    - /var/lib/postgresql/data/
  ports:
    - "5432"
  environment:
    - POSTGRES_USER=pactbroker
    - POSTGRES_PASSWORD=supersave
web:
  image: flowerpot/pact-broker-pg-docker
  ports:
    - "5000:5000"
  links:
    - db
  environment:
    - DATABASE_URL=postgres://pactbroker:supersave@db/pactbroker
    #- PACT_BROKER_USERNAME=admin
    #- PACT_BROKER_PASSWORD=admin

